### ISSUE TITLE
Potential BUG: Interactions are not publishing the contract owner

### ISSUE THREAD

**Issue by twilson63** [warp-contracts/gateway#105]
It looks like since the last commit that the contract owner is not getting published as part of the interaction, if you look in sonar you can see interactions are being created without owners

See:
https://sonar.warp.cc/#/app/contract/aSMILD7cEJr93i7TAVzzMjtci_sGkXcWnqpDkG6UGcA

From looking at the code it appears there is an `await` in a function that is not set to `async` on line 244, also that function is being invoked as a synchronous function, so my guess the `await arweave.wallets.ownerToAddress(originalOwner)` is not being run and returning an empty `originalAddress`

https://github.com/warp-contracts/gateway/blob/67dd4a84e9541109b96d661ac35efd4796b35626/src/gateway/router/routes/sequencerRoute.ts#L244

**Comment by asiaziola** [comment]
Hey @twilson63! Everything seems to be fine now. You were right - this bug results from a silly mistake of not including await :) Fortunately, I was able to fix it for new coming txs as well as invalid. We keep some additional data which let us restore the malfunctioning fields. 

Thank you for reporting this issue, it enabled us to fix it so quickly :)
