### ISSUE TITLE
fix: sequencer should save bundled tx actual price and not the Arweave reward

### ISSUE THREAD

**Issue by asiaziola** [warp-contracts/gateway#43]
One possible solution to achieve that would be to use `getPrice()` Bundlr method and calculate it based on transaction's size.

**Comment by ppedziwiatr** [comment]
I've talked with the Bundlr team, they should soon add the fee to the object returned from the `transaction.upload()` method
They will also add proper tags to all bundles that contain at least one SmartWeave interaction
